name: mafactory
recipe: wordpress
services:
  appserver:
    overrides:
      environment:
        DB_NAME: innovatibv3
        DB_USER: root
        DB_PASSWORD: 
        DB_HOST: database
        WP_ENV: development
        WP_SITEURL: https://innovation-factory.lndo.site/wp
        WP_HOME: https://innovation-factory.lndo.site

  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mailhog.innovation-factory.lndo.site
  
config:
  php: '8.1'
  webroot: web 

