name: mafactory
recipe: wordpress
services:
  appserver:
    overrides:
      environment:
        DB_NAME: wordpress
        DB_USER: root
        DB_PASSWORD: 
        DB_HOST: database
        DB_PREFIX: mf_
        WP_ENV: production
        WP_SITEURL: https://mafactory.lndo.site/wp
        WP_HOME: https://mafactory.lndo.site

  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mailhog.mafactory.lndo.site
  
config:
  php: '8.1
    '
  webroot: web 

